name: Build & Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: npm install
      env:
        CI: true

    - name: Lint
      run: npm run lint

    - name: Build
      run: |
        npm run make_cmdline
        npm run make_ide

    - name: Test
      run: npm test

